name: Build Multi-Platform Releases

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.0)'
        required: true
        default: 'v1.2.0'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Windows EXE
      run: |
        # Создаем spec файл для Windows
        echo 'a = Analysis(["launcher.py"], pathex=[], binaries=[], datas=[("templates", "templates"), ("static", "static"), ("app.py", "."), ("cisco_manager.py", "."), ("requirements.txt", "."), ("README.md", ".")], hiddenimports=["flask", "netmiko", "paramiko", "flask_cors", "werkzeug", "jinja2"], hookspath=[], hooksconfig={}, runtime_hooks=[], excludes=[], noarchive=False)
        pyz = PYZ(a.pure)
        exe = EXE(pyz, a.scripts, a.binaries, a.datas, [], name="CiscoConfigManager", debug=False, bootloader_ignore_signals=False, strip=False, upx=True, upx_exclude=[], runtime_tmpdir=None, console=False, disable_windowed_traceback=False)' > launcher.spec
        
        pyinstaller launcher.spec --clean --noconfirm
    
    - name: Create Windows package
      run: |
        mkdir release-windows
        copy dist\CiscoConfigManager.exe release-windows\
        copy README.md release-windows\
        copy LICENSE release-windows\
        echo "Cisco Configuration Manager for Windows" > release-windows\README.txt
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cisco-config-manager-windows
        path: release-windows/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build Linux executable
      run: |
        # Создаем spec файл для Linux
        cat > launcher.spec << 'EOF'
        a = Analysis(['launcher.py'], pathex=[], binaries=[], 
            datas=[('templates', 'templates'), ('static', 'static'), ('app.py', '.'), 
                   ('cisco_manager.py', '.'), ('requirements.txt', '.'), ('README.md', '.')],
            hiddenimports=['flask', 'netmiko', 'paramiko', 'flask_cors', 'werkzeug', 'jinja2'],
            hookspath=[], hooksconfig={}, runtime_hooks=[], excludes=[], noarchive=False)
        
        pyz = PYZ(a.pure)
        exe = EXE(pyz, a.scripts, a.binaries, a.datas, [], name='CiscoConfigManager',
            debug=False, bootloader_ignore_signals=False, strip=False, upx=True,
            upx_exclude=[], runtime_tmpdir=None, console=False, disable_windowed_traceback=False)
        EOF
        
        pyinstaller launcher.spec --clean --noconfirm
    
    - name: Create Linux package
      run: |
        mkdir release-linux
        cp dist/CiscoConfigManager release-linux/
        cp README.md release-linux/
        cp LICENSE release-linux/
        cp setup.sh release-linux/
        chmod +x release-linux/CiscoConfigManager
        echo "Cisco Configuration Manager for Linux" > release-linux/README.txt
    
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cisco-config-manager-linux
        path: release-linux/

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build macOS application
      run: |
        # Создаем spec файл для macOS
        cat > launcher.spec << 'EOF'
        a = Analysis(['launcher.py'], pathex=[], binaries=[], 
            datas=[('templates', 'templates'), ('static', 'static'), ('app.py', '.'), 
                   ('cisco_manager.py', '.'), ('requirements.txt', '.'), ('README.md', '.')],
            hiddenimports=['flask', 'netmiko', 'paramiko', 'flask_cors', 'werkzeug', 'jinja2'],
            hookspath=[], hooksconfig={}, runtime_hooks=[], excludes=[], noarchive=False)
        
        pyz = PYZ(a.pure)
        exe = EXE(pyz, a.scripts, a.binaries, a.datas, [], name='CiscoConfigManager',
            debug=False, bootloader_ignore_signals=False, strip=False, upx=True,
            upx_exclude=[], runtime_tmpdir=None, console=False, disable_windowed_traceback=False)
        EOF
        
        pyinstaller launcher.spec --clean --noconfirm
    
    - name: Create macOS package
      run: |
        mkdir release-macos
        cp dist/CiscoConfigManager release-macos/
        cp README.md release-macos/
        cp LICENSE release-macos/
        chmod +x release-macos/CiscoConfigManager
        echo "Cisco Configuration Manager for macOS" > release-macos/README.txt
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cisco-config-manager-macos
        path: release-macos/

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create release packages
      run: |
        # Создаем архивы для каждой платформы
        cd cisco-config-manager-windows && zip -r ../CiscoConfigManager-Windows.zip . && cd ..
        cd cisco-config-manager-linux && tar -czf ../CiscoConfigManager-Linux.tar.gz . && cd ..
        cd cisco-config-manager-macos && tar -czf ../CiscoConfigManager-macOS.tar.gz . && cd ..
        
        # Показываем размеры
        ls -lh *.zip *.tar.gz
    
    - name: Get version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: 🌐 Cisco Configuration Manager ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## 🎉 Cisco Configuration Manager ${{ steps.get_version.outputs.VERSION }}
          
          ### ✨ Новые возможности
          - 🌙 **Темный режим** с автоматическим определением системных настроек
          - 🔘 **Одноклчиковый запуск** - готовые исполняемые файлы для всех платформ
          - 📱 **Современный интерфейс** с Bootstrap 5
          - ⚡ **Быстрая установка** всех зависимостей
          
          ### 🚀 Скачать для вашей ОС
          
          | Платформа | Файл | Размер | Описание |
          |-----------|------|--------|----------|
          | 🪟 **Windows** | `CiscoConfigManager-Windows.zip` | ~20MB | EXE файл с GUI лаунчером |
          | 🐧 **Linux** | `CiscoConfigManager-Linux.tar.gz` | ~20MB | Исполняемый файл + setup.sh |
          | 🍎 **macOS** | `CiscoConfigManager-macOS.tar.gz` | ~20MB | Приложение для macOS |
          
          ### 📋 Как использовать
          
          1. **Скачайте** архив для вашей ОС
          2. **Распакуйте** архив
          3. **Запустите** исполняемый файл
          4. **Нажмите** "🚀 Установить и запустить"
          5. **Ждите** автоматического открытия браузера
          
          ### 🌐 Интерфейс
          После запуска приложение будет доступно: http://localhost:5000
          
          ### 📞 Поддержка
          - 🐛 **Баги:** Создайте Issue
          - 💡 **Предложения:** Pull Requests приветствуются
          
          ---
          
          **Лицензия:** MIT | **Язык:** Русский | **Python:** 3.7+
        files: |
          CiscoConfigManager-Windows.zip
          CiscoConfigManager-Linux.tar.gz
          CiscoConfigManager-macOS.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
